name: Build Driver for Luckfox
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Pure Kernel Headers
        run: |
          mkdir ~/headers && cd ~/headers
          git init
          git remote add origin https://github.com
          git config core.sparseCheckout true
          echo "include/linux/*" >> .git/info/sparse-checkout
          echo "include/uapi/*" >> .git/info/sparse-checkout
          git pull --depth 1 origin v5.10
          
      - name: Upload Safe Archive
        uses: actions/upload-artifact@v4
        with:
          name: luckfox-driver
          path: ~/headers/include/
