name: Build Driver for Luckfox
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools and Kernel Headers
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf make git linux-headers-generic
      - name: Compile Driver
        run: |
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -C /lib/modules/$(ls /lib/modules | head -n 1)/build M=$(pwd) modules
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: luckfox-driver
          path: "*.ko"
